# Generated by Django 2.2.6 on 2019-10-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('yogaclass', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('bio', models.TextField()),
                ('photo', models.FilePathField(path='/img')),
                ('hometown', models.CharField(max_length=32)),
                ('philosophy', models.TextField()),
                ('experience', models.TextField()),
                ('certifications', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('classes', models.ManyToManyField(to='instructor.Class')),
            ],
        ),
    ]
